APGP = {
    ["zypha"] = {
        ["AP"] = 1300,
        ["GP"] = 650,
        ["sum_cost"] = 0
    }, -- [1]
    ["theintersect"] = {
        ["AP"] = 1500,
        ["GP"] = 1000,
        ["sum_cost"] = 0
    }, -- [2]
    ["mindlini"] = {
        ["AP"] = 600,
        ["GP"] = 50,
        ["sum_cost"] = 0
    }, -- [3]
    ["mentop"] = {
        ["AP"] = 1500,
        ["GP"] = 780,
        ["sum_cost"] = 0
    }, -- [4]
}
